#!/usr/bin/env bash
# Configure Nginx so that its HTTP response contains a custom header (on web-01 and web-02)
# The name of the custom HTTP header must be X-Served-By
# The value of the custom HTTP header must be the hostname of the server Nginx is running on

sudo apt-get -y update
sudo apt-get -y install nginx

sudo ufw allow 'Nginx HTTP'

sudo mkdir -p /var/www/html /var/www/error
sudo chmod -R 755 /var/www/html /var/www/error

echo 'Hello World!" | sudo tee /var/www/html/index.html > dev/null
echo 'Ceci n'est pas une page" | sudo tee /var/www/error/404.html > dev/null

server_config=$(cat <<EOF
server {
	listen 80 default_server;
    	listen [::]:80 default_server;

	root /var/www/html;
	index index.html index.htm index.nginx-debian.html;

	server_name _;

	location / {
		try_files \$uri \$uri/ =404;
	}

	error_page 404 /404.html;
	location = /404.html {
		root /var/www/error;
		internal;
	}

	add_header X-Served-By $HOSTNAME;
}
EOF
)

echo "$server_config" | sudo tee /etc/nginx/sites-available/default > /dev/null

sudo service nginx restart