#!/usr/bin/env bash
# Bash script that pings an IP address passed as an argument
# Accepts a string as an argument
# Usage: 5-is_the_host_on_the_network {IP_ADDRESS} if no argument is passed
# ping the IP 5 times

if [ -z "$1"]; then
	echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
else
	ping -c 5 "$1"
fi
