#!/usr/bin/env bash
# Creates the file /var/run/myscript.pid containig its PID
# Displays To infinity and beyond indefinitely
# Displays I hate the kill command when receiving a SIGTERM signal
# Displays Y U no love me?! when recieving a SIGINT signal
# Deletes the file /var/run/myscript.pid and terminates when receiving a SIGQUIT or SIGTERM signal

touch /var/run/myscript.pid && echo $$ > /var/run/myscript.pid

sigterm_handler() {
	echo "I hate the kill command"
	rm /var/run/myscript.pid
}

sigint_handler() {
	echo "Y U no love me?!"
}

sigquit_handler() {
	rm /var/run/myscript.pid
}
trap sigterm_handler SIGTERM
trap sigint_handler SIGINT
trap sigquit_handler SIGQUIT

while true; do
	echo "To infinity and beyond"
done
