#!/usr/bin/env bash
# Configures a firewall for select ports for incoming traffic
# allows all outgoing traffic

sudo apt install ufw
sudo ufw default deny incoming
sudo ufw default allow outgoing
sudo ufw allow 22/tcp
sudo ufw allow 443/tcp
sudo ufw allow 80/tcp
sudo ufw enable
sudo ufw status
