#!/usr/bin/env bash
#Configures an ubuntu server such that localhost resolves to 127.0.0.2 and facebook.com resolves to 8.8.8.8
cp /etc/hosts ~/hosts.new
sed -i 's/127.*$/127.0.0.2 localhost\n8.8.8.8 facebook.com/' ~/hosts.new
sudo cp -f ~/hosts.new /etc/hosts
